### ISSUE TITLE
[Question] HW6 various tests not passing

### ISSUE THREAD

**Issue by ilchu** [kaist-cp/cs431#595]
I have three points I can't wrap my head around.

1) My code passes tests in `hazard.rs` and `retire.rs` besides `all_hazards_protected` with `cargo_asan`. It announces a leak when I make new slots with `Box::leak()` in `acquire_slot()` function. Shouldn't this be intended behavior and if not, why only this test fails with ASan?

2) The integration tests sometimes get stuck, but sometimes pass okay. When I try to debug and add print statements, it usually happens after one RetiredSet drop as that message is printed after a bunch of shield drops at the end of a spawned thread's execution. However, when I try to debug it, all of the threads seem to have either already exited (i.e. with no variable info in vscode in the debug panel, no further step through button pressable, no error), or, even more confusingly, the test passes perfectly when I put a breakpoint at the end of the `scope()` call. I have zero idea what to do with it and what it could be caused by. I started suspecting a rather unconventional (maybe?) way to clear out the `RetiredSet` using `Vec::retain()`, but maybe I'm overthinking things?

3) Both sync tests besides `protect_collect_sync` pass, with the latter giving a very cryptic backlog:
<details>
<summary>Backlog</summary>

```sh
thread 'sync::protect_collect_sync' panicked at 'Model exeeded maximum number of branches. This is often caused by an algorithm requiring the processor to make progress, e.g. spin locks.', /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/path.rs:131:9
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:543:12
   1: loom::rt::path::Path::push_load
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/path.rs:131:9
   2: loom::rt::atomic::Atomic<T>::load::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/atomic.rs:240:17
   3: loom::rt::synchronize::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:126:9
   4: loom::rt::scheduler::Scheduler::with_execution::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:48:34
   5: loom::rt::scheduler::Scheduler::with_state::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:130:28
   6: scoped_tls::ScopedKey<T>::with
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:171:13
   7: loom::rt::scheduler::Scheduler::with_state
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:130:9
   8: loom::rt::scheduler::Scheduler::with_execution
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:48:9
   9: loom::rt::execution
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:156:5
  10: loom::rt::synchronize
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:123:5
  11: loom::rt::atomic::Atomic<T>::load
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/atomic.rs:231:9
  12: loom::sync::atomic::atomic::Atomic<T>::load
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/sync/atomic/atomic.rs:28:9
  13: loom::sync::atomic::ptr::AtomicPtr<T>::load
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/sync/atomic/ptr.rs:37:9
  14: cs431_homework::hazard_pointer::hazard::Shield<T>::try_protect
             at ./src/hazard_pointer/hazard.rs:39:23
  15: cs431_homework::hazard_pointer::hazard::Shield<T>::protect
             at ./src/hazard_pointer/hazard.rs:52:16
  16: hazard_pointer::sync::protect_collect_sync::{{closure}}::{{closure}}
             at ./tests/hazard_pointer.rs:273:33
  17: loom::thread::spawn_internal::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/thread.rs:159:47
  18: loom::rt::spawn::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:76:9
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  21: loom::rt::scheduler::spawn_threads::{{closure}}::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:149:21
  22: generator::gen_impl::GeneratorImpl<A,T>::init_code::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/gen_impl.rs:348:21
  23: generator::stack::StackBox<F>::call_once
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/stack/mod.rs:139:13
  24: generator::stack::Func::call_once
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/stack/mod.rs:121:9
  25: generator::gen_impl::gen_init::{{closure}}
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/gen_impl.rs:550:9
  26: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  27: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  28: __rust_try
  29: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  30: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  31: generator::gen_impl::gen_init
             at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/gen_impl.rs:564:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'sync::protect_collect_sync' panicked at 'Model exeeded maximum number of branches. This is often caused by an algorithm requiring the processor to make progress, e.g. spin locks.', /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/path.rs:199:13
stack backtrace:
   0:     0x560cfaeba45c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x560cfaeba45c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560cfaeba45c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560cfaeba45c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560cfaedeadc - core::fmt::write::h2a1462b5f8eea807
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
   5:     0x560cfaeb6405 - std::io::Write::write_fmt::h71ddfebc68685972
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
   6:     0x560cfaebc410 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x560cfaebc410 - std::sys_common::backtrace::print::h335a66af06738c7c
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x560cfaebc410 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
   9:     0x560cfaebbfc5 - std::panicking::default_hook::h341c1030c6a1161b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
  10:     0x560cfaebcac4 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
  11:     0x560cfaddd2a2 - std::panicking::begin_panic::{{closure}}::h1b89cc6a9f0c65b3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:544:9
  12:     0x560cfadd6dc9 - std::sys_common::backtrace::__rust_end_short_backtrace::hf940603df819fbdb
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x560cfaddd1e3 - std::panicking::begin_panic::h11022e2314b2fb38
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:543:12
  14:     0x560cfabcb6c9 - loom::rt::path::Path::branch_thread::h8da13a585ba220ff
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/path.rs:199:13
  15:     0x560cfab8de64 - loom::rt::execution::Execution::schedule::h4a906223e4279ca0
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/execution.rs:182:20
  16:     0x560cfabadcf6 - loom::rt::branch::{{closure}}::h14601b06e58c4e78
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:105:22
  17:     0x560cfaba9eda - loom::rt::scheduler::Scheduler::with_execution::{{closure}}::hfa17f7ae886fb9de
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:48:34
  18:     0x560cfabad1a5 - loom::rt::scheduler::Scheduler::with_state::{{closure}}::hc4352eafc0dd002b
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:130:28
  19:     0x560cfabb3701 - scoped_tls::ScopedKey<T>::with::h5434dc2fbe4041ee
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:171:13
  20:     0x560cfabaa4a2 - loom::rt::scheduler::Scheduler::with_state::h1fa67471cbb35c42
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:130:9
  21:     0x560cfaba9669 - loom::rt::scheduler::Scheduler::with_execution::hbd582597705511e3
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:48:9
  22:     0x560cfabb1e79 - loom::rt::execution::h83026e1b6ea71125
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:156:5
  23:     0x560cfabadc69 - loom::rt::branch::hcdec7bcb496e77e7
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:103:25
  24:     0x560cfaba616e - loom::rt::object::Ref<T>::branch_action::h08b0c6799fee1779
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/object.rs:346:9
  25:     0x560cfab857ab - loom::rt::atomic::Atomic<T>::branch::he7cf603fbcb8fc05
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/atomic.rs:389:9
  26:     0x560cfab83da0 - loom::rt::atomic::Atomic<T>::store::h6c481338b1c53a87
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/atomic.rs:274:9
  27:     0x560cfabc5ce3 - loom::sync::atomic::atomic::Atomic<T>::store::h8b1570a9ffdcbdea
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/sync/atomic/atomic.rs:33:9
  28:     0x560cfaba862e - loom::sync::atomic::bool::AtomicBool::store::h44536c5628171cd2
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/sync/atomic/bool.rs:38:9
  29:     0x560cfab255d6 - <cs431_homework::hazard_pointer::hazard::Shield<T> as core::ops::drop::Drop>::drop::h4f6c216770cfe817
                               at /home/s20170857/new/cs431/homework/src/hazard_pointer/hazard.rs:70:9
  30:     0x560cfab23d0a - core::ptr::drop_in_place<cs431_homework::hazard_pointer::hazard::Shield<usize>>::h1c7645ed9cb6f7fb
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ptr/mod.rs:188:1
  31:     0x560cfab292d8 - hazard_pointer::sync::protect_collect_sync::{{closure}}::{{closure}}::hc56d94b355039f51
                               at /home/s20170857/new/cs431/homework/tests/hazard_pointer.rs:278:17
  32:     0x560cfab2a9c7 - loom::thread::spawn_internal::{{closure}}::he5edc94901e388db
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/thread.rs:159:47
  33:     0x560cfaafb4c0 - loom::rt::spawn::{{closure}}::hbe689fab0cbc0033
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/mod.rs:76:9
  34:     0x560cfab220fe - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9266d8e690211c6d
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  35:     0x560cfabbec0d - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2931331b661dd4a3
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
  36:     0x560cfabad9c8 - loom::rt::scheduler::spawn_threads::{{closure}}::{{closure}}::h66b4ec88c527cd1d
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.5.4/src/rt/scheduler.rs:149:21
  37:     0x560cfaba3dbd - generator::gen_impl::GeneratorImpl<A,T>::init_code::{{closure}}::h1e33b9e49ecc190e
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/gen_impl.rs:348:21
  38:     0x560cfab8b98b - generator::stack::StackBox<F>::call_once::h1741e50777387ed6
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/stack/mod.rs:139:13
  39:     0x560cfae87c4b - generator::stack::Func::call_once::h85c3e62386cfea73
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/stack/mod.rs:121:9
  40:     0x560cfae89923 - generator::gen_impl::gen_init::{{closure}}::ha296166a3e96a460
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/gen_impl.rs:550:9
  41:     0x560cfae8b0f3 - core::ops::function::FnOnce::call_once::h6dddcab4d78b7533
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  42:     0x560cfae896ee - std::panicking::try::do_call::h017b5996ce3d39ec
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  43:     0x560cfae89c1b - __rust_try
  44:     0x560cfae89654 - std::panicking::try::h990d151c3179c86a
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  45:     0x560cfae8a88f - std::panic::catch_unwind::hf03a72e591ccdc2b
                               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  46:     0x560cfae897d4 - generator::gen_impl::gen_init::hc97000751e0be290
                               at /home/s20170857/.cargo/registry/src/github.com-1ecc6299db9ec823/generator-0.7.0/src/gen_impl.rs:564:25
  47:                0x0 - <unknown>
thread panicked while panicking. aborting.
error: test failed, to rerun pass '--test hazard_pointer'

Caused by:
  process didn't exit successfully: `/home/s20170857/new/cs431/homework/target/debug/deps/hazard_pointer-a38613e51b36790e --exact 'sync::protect_collect_sync' --nocapture` (signal: 4, SIGILL: illegal instruction)

```

</details>

Could you help with figuring out what it could mean?

**Comment by tomtomjhj** [comment]
1. `impl Drop for HazardBag` should free the slots.
2. Possible cause: `impl Drop for RetiredSet` loops until the thread's retired pointers are all reclaimed. So if the test loops infinitely when dropping `RetiredSet`, something is preventing the reclamation. This can happen if `impl<T> Drop for Shield<T>` does not clear the hazard slot properly.
3. Are you using loops in `try_protect` and `impl<T> Drop for Shield<T>`? They can be implmented without loops. Also can you try adding this to end of any loops in your implementation? See `protect` for an example.
    ```rust
    #[cfg(feature = "check-loom")]
    loom::sync::atomic::spin_loop_hint();
    ```

**Comment by ilchu** [comment]
1. I suppose it does so already, by loading the head pointer of the bag and then walking all the next ones in a loop, consuming each pointer with `Box::from_raw()`.
2. I'm clearing it just like the paper, by first loading the shield's slot into a mutable reference and then resetting the active flag and pointing the hazard to zero via atomic operations and doing nothing besides.
3. Neither of these two has any loops in my implementation. Also, I tried adding the hint to all the loops I have, but it had no effect on the error.

**Comment by tomtomjhj** [comment]
1. When you insert the new slot to the bag, how do you handle the CAS failure case?
2. Hmm... can you exactly identify the point where the test gets stuck? For example, try adding prints in all loops.
3. That's interesting. I think I should inspect your solution to check if there's actually a problem. Please send your code to jaehwang.jung@kaist.ac.kr

**Comment by ilchu** [comment]
Turns out the problem was remembering to update the `*pointer` in the shield validation step, and once I fixed that it got everything working. Thank you for all your help!
